/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;
import italler.Cliente;
import italler.Coche;
import italler.ctrlTaller;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ArclorenSarth
 */
public class iTallerUI extends javax.swing.JFrame {
    
    ctrlTaller taller;
    DefaultTableModel tabCli;
    DefaultTableModel tabCch;
    ArrayList<Cliente> clientes;
    ArrayList<Coche> coches;
    /**
     * Creates new form iTallerUI
     */
    public iTallerUI() {
        initComponents();
        taller = ctrlTaller.getInstance();
        initTablasClientes();
        initTablasCoches();
    }
    
    private void initTablasClientes(){
        tabCli = (DefaultTableModel) tablaClientes.getModel();
        clientes = taller.searchClientes("");
        tabCli.setNumRows(clientes.size());
                
        for(int i=0; i<clientes.size(); ++i){
            tablaClientes.setValueAt(clientes.get(i).getNombre(), i, 0);
            tablaClientes.setValueAt(clientes.get(i).getDNI(), i, 1);
            tablaClientes.setValueAt(clientes.get(i).getTlf(), i, 2);
            tablaClientes.setValueAt(clientes.get(i).getMvl(), i, 3);
            tablaClientes.setValueAt(clientes.get(i).getMail(), i, 4);
            tablaClientes.setValueAt(clientes.get(i).getDir(), i, 5);
        }
                     
    }
    
    
    private void initTablasCoches(){
        tabCch = (DefaultTableModel) tablaCoches.getModel();
        coches = taller.searchCoches("");
        tabCch.setNumRows(coches.size());
               
        for(int i=0; i<coches.size(); ++i){
            tablaCoches.setValueAt(coches.get(i).getMatricula(), i, 0);
            tablaCoches.setValueAt(coches.get(i).getMarca(), i, 1);
            tablaCoches.setValueAt(coches.get(i).getModelo(), i, 2);
            tablaCoches.setValueAt(coches.get(i).getNumKm(), i, 3);
            tablaCoches.setValueAt(coches.get(i).getNumBast(), i, 4);
            tablaCoches.setValueAt(coches.get(i).getPropietario(), i, 5);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        buscarBut = new javax.swing.JButton();
        buscarText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        matriculaCheck = new javax.swing.JRadioButton();
        nombreCheck = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        addClienteButton = new javax.swing.JButton();
        editClienteButton = new javax.swing.JButton();
        deleteClienteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCoches = new javax.swing.JTable();
        addCchButton = new javax.swing.JButton();
        modCchButton = new javax.swing.JButton();
        delCchButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        buscarBut.setText("Buscar");
        buscarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButActionPerformed(evt);
            }
        });

        buscarText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTextActionPerformed(evt);
            }
        });

        jLabel1.setText("BUSCAR UNA FACTURA");

        matriculaCheck.setText("por matricula");
        matriculaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaCheckActionPerformed(evt);
            }
        });

        nombreCheck.setText("por nombre");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buscarBut)
                .addGap(32, 32, 32))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(matriculaCheck)
                        .addGap(38, 38, 38)
                        .addComponent(nombreCheck))
                    .addComponent(buscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarBut)
                    .addComponent(buscarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculaCheck)
                    .addComponent(nombreCheck))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Facturas", jPanel1);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "DNI", "Telefono", "Movil", "Mail", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tablaClientes);

        addClienteButton.setText("Añadir Cliente");
        addClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteButtonActionPerformed(evt);
            }
        });

        editClienteButton.setText("Modificar Cliente");
        editClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClienteButtonActionPerformed(evt);
            }
        });

        deleteClienteButton.setText("Eliminar Cliente");
        deleteClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClienteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editClienteButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteClienteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addClienteButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClienteButton)
                    .addComponent(editClienteButton)
                    .addComponent(deleteClienteButton))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        tablaCoches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Marca", "Modelo", "Nº Km", "Nº Bastidor", "Propietario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaCoches);

        addCchButton.setText("Añadir Coche");
        addCchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCchButtonActionPerformed(evt);
            }
        });

        modCchButton.setText("Modificar Vehiculo");
        modCchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modCchButtonActionPerformed(evt);
            }
        });

        delCchButton.setText("Eliminar Vehiculo");
        delCchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(modCchButton)
                        .addGap(18, 18, 18)
                        .addComponent(delCchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCchButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCchButton)
                    .addComponent(modCchButton)
                    .addComponent(delCchButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vehiculos", jPanel3);

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("iTaller - Talleres Ronda");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButActionPerformed
        
        //buscarText.setText(t.get(0));
        searchFacturas searchWind;
        searchWind = new searchFacturas();
        searchWind.buscarMatricula(buscarText.getText());
        searchWind.setLocationRelativeTo(null);
        searchWind.show(true);
        
        //taller.abrirFactura(t.get(0));
    }//GEN-LAST:event_buscarButActionPerformed

    private void buscarTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTextActionPerformed

    private void matriculaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaCheckActionPerformed

    private void addClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteButtonActionPerformed
        crearClienteWnd cw = new crearClienteWnd(new javax.swing.JFrame(),true,null);
        cw.setLocationRelativeTo(null);
        cw.show();
        initTablasClientes();
    }//GEN-LAST:event_addClienteButtonActionPerformed

    private void deleteClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClienteButtonActionPerformed
        if(tablaClientes.getSelectedRow() >= 0){
            askWind a = new askWind(new javax.swing.JFrame(),true,"Seguro que desea eliminar este cliente?");
            a.setLocationRelativeTo(null);
            a.show();
            if(a.getValue() == true){
                try{
                    taller.eliminarCliente(clientes.get(tablaClientes.getSelectedRow()).getNombre());
                    initTablasClientes();
                    initTablasCoches();
                }
                catch(Exception e){
                    excepWind w = new excepWind(new javax.swing.JFrame(),true,e.getMessage());
                    w.show();
                }
            }
            a.dispose();
        }
        
    }//GEN-LAST:event_deleteClienteButtonActionPerformed

    private void editClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClienteButtonActionPerformed
        crearClienteWnd cw = new crearClienteWnd(new javax.swing.JFrame(),true,
                                 clientes.get(tablaClientes.getSelectedRow()));
        cw.show();
        initTablasClientes();
        initTablasCoches();
    }//GEN-LAST:event_editClienteButtonActionPerformed

    private void modCchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modCchButtonActionPerformed
        crearCocheWnd cw = new crearCocheWnd(new javax.swing.JFrame(),true,
                                 coches.get(tablaCoches.getSelectedRow()));
        cw.show();
        initTablasCoches();
    }//GEN-LAST:event_modCchButtonActionPerformed

    private void delCchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCchButtonActionPerformed
        if(tablaCoches.getSelectedRow() >= 0){
            askWind a = new askWind(new javax.swing.JFrame(),true,"Seguro que desea eliminar este vehiculo?");
            a.setLocationRelativeTo(null);
            a.show();
            if(a.getValue() == true){
                try{
                    taller.eliminarCoche(coches.get(tablaCoches.getSelectedRow()).getMatricula());
                    initTablasCoches();
                }
                catch(Exception e){
                    excepWind w = new excepWind(new javax.swing.JFrame(),true,e.getMessage());
                    w.show();
                }
            }
            a.dispose();
        }
    }//GEN-LAST:event_delCchButtonActionPerformed

    private void addCchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCchButtonActionPerformed
        crearCocheWnd cw = new crearCocheWnd(new javax.swing.JFrame(),true,null);
        cw.setLocationRelativeTo(null);
        cw.show();
        initTablasCoches();
    }//GEN-LAST:event_addCchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iTallerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iTallerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iTallerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iTallerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iTallerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCchButton;
    private javax.swing.JButton addClienteButton;
    private javax.swing.JButton buscarBut;
    private javax.swing.JTextField buscarText;
    private javax.swing.JButton delCchButton;
    private javax.swing.JButton deleteClienteButton;
    private javax.swing.JButton editClienteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton matriculaCheck;
    private javax.swing.JButton modCchButton;
    private javax.swing.JRadioButton nombreCheck;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaCoches;
    // End of variables declaration//GEN-END:variables
}
