/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import italler.Cliente;
import italler.Coche;
import italler.ctrlTaller;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ArclorenSarth
 */
public class searchFacturas extends javax.swing.JFrame {
    
    ctrlTaller taller;
    DefaultTableModel tabFac;
    ArrayList<String> facs;
    DefaultListModel cochesModel;
    
    /**
     * Creates new form searchFacturas
     */
    public searchFacturas() {
        initComponents();
        taller = ctrlTaller.getInstance();
        initTabla(0);
        
    }
    
    public void buscarMatricula(String text){
        facs = taller.searchFacturas(text);
        initTabla(facs.size());
        System.out.println("rows = " + facs.size());
        
        
        
    }
    
    public void buscarCliente(String text){
        
    }
    
    private void initTabla(int rows){
        /*tabFac=new DefaultTableModel();
        tabFac.addColumn("Fecha");
        tabFac.addColumn("Matricula");
        tabFac.setNumRows(rows);
        tablaFacturas.setModel(tabFac);*/
        tabFac = (DefaultTableModel) tablaFacturas.getModel();
        tabFac.setNumRows(rows);
        for(int i=0; i < rows; ++i){
            tablaFacturas.setValueAt(fecha(facs.get(i)), i, 0);
            tablaFacturas.setValueAt(matricula(facs.get(i)), i, 1);
        }
        
    }
    
    String matricula(String text){
        String[] dirs = text.split("/");
        String file = dirs[dirs.length-1];
        int dot = file.indexOf('.',10);
        System.out.println("mat:" + file.substring(11,dot));
        return file.substring(11,dot);
    }
    
    String fecha(String text){
        String[] dirs = text.split("/");
        String file = dirs[dirs.length-1];
        return file.substring(0,10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        tlfText = new javax.swing.JTextField();
        tlfLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        mailText = new javax.swing.JTextField();
        DNILabel = new javax.swing.JLabel();
        dniText = new javax.swing.JTextField();
        movilLabel = new javax.swing.JLabel();
        mvlText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsText = new javax.swing.JTextArea();
        observLabel = new javax.swing.JLabel();
        abrirFacButton = new javax.swing.JToggleButton();
        modClntButton = new javax.swing.JToggleButton();
        saveClntButton = new javax.swing.JToggleButton();
        borrarFacButton = new javax.swing.JButton();
        dirLabel = new javax.swing.JLabel();
        dirText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        marcaText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        modeloText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kmText = new javax.swing.JTextField();
        bastText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        modCochtButton = new javax.swing.JToggleButton();
        modCochButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cochesList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaFacturas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Datos del cliente");

        nombreLabel.setText("Nombre");

        nombreText.setText("-NA-");
        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });

        tlfText.setText("-NA-");

        tlfLabel.setText("Tlf");

        mailLabel.setText("Mail");

        mailText.setText("-NA-");

        DNILabel.setText("DNI");

        dniText.setText("-NA-");
        dniText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTextActionPerformed(evt);
            }
        });

        movilLabel.setText("Mvl");

        mvlText.setText("-NA-");
        mvlText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvlTextActionPerformed(evt);
            }
        });

        obsText.setColumns(20);
        obsText.setRows(5);
        obsText.setText("-NA-");
        jScrollPane1.setViewportView(obsText);

        observLabel.setText("Observaciones");

        abrirFacButton.setText("Abrir Factura");
        abrirFacButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirFacButtonActionPerformed(evt);
            }
        });

        modClntButton.setText("Modificar Cliente");
        modClntButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modClntButtonActionPerformed(evt);
            }
        });

        saveClntButton.setText("Guardar Cliente");
        saveClntButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveClntButtonActionPerformed(evt);
            }
        });

        borrarFacButton.setText("Borrar Factura");

        dirLabel.setText("Dir.");

        dirText.setText("-NA-");
        dirText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Datos del coche");

        jLabel4.setText("Marca");

        marcaText.setText("-NA-");
        marcaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaTextActionPerformed(evt);
            }
        });

        jLabel5.setText("Modelo");

        modeloText.setText("-NA-");

        jLabel6.setText("nº Bast.");

        kmText.setText("-NA-");

        bastText.setText("-NA-");
        bastText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bastTextActionPerformed(evt);
            }
        });

        jLabel7.setText("nº Km");

        jLabel8.setText("Coches del cliente");

        modCochtButton.setText("Modificar Coche");

        modCochButton.setText("Modificar Coche");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("FACTURAS");

        jScrollPane4.setViewportView(cochesList);

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha", "Matricula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaFacturasMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tablaFacturas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(300, 300, 300)
                        .addComponent(observLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreLabel)
                            .addComponent(dirLabel)
                            .addComponent(mailLabel)
                            .addComponent(DNILabel))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dirText, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mailText, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dniText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(movilLabel)
                                .addGap(4, 4, 4)
                                .addComponent(mvlText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(tlfLabel)
                                .addGap(4, 4, 4)
                                .addComponent(tlfText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(modClntButton)
                        .addGap(9, 9, 9)
                        .addComponent(saveClntButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(456, 456, 456)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(marcaText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(modeloText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(modCochtButton)
                                .addGap(6, 6, 6)
                                .addComponent(modCochButton)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kmText, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bastText, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(borrarFacButton))
                            .addComponent(abrirFacButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(observLabel)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nombreLabel)
                        .addGap(7, 7, 7)
                        .addComponent(dirLabel)
                        .addGap(7, 7, 7)
                        .addComponent(mailLabel)
                        .addGap(6, 6, 6)
                        .addComponent(DNILabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(dirText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(mailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dniText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(movilLabel))
                            .addComponent(mvlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(tlfLabel))
                            .addComponent(tlfText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modClntButton)
                    .addComponent(saveClntButton))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(marcaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modeloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel5)))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modCochtButton)
                                    .addComponent(modCochButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kmText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(bastText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(borrarFacButton)
                    .addComponent(abrirFacButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextActionPerformed

    private void dniTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTextActionPerformed

    private void modClntButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modClntButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modClntButtonActionPerformed

    private void saveClntButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveClntButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveClntButtonActionPerformed

    private void abrirFacButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirFacButtonActionPerformed
        taller.abrirFactura(facs.get(tablaFacturas.getSelectedRow()));
    }//GEN-LAST:event_abrirFacButtonActionPerformed

    private void mvlTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvlTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvlTextActionPerformed

    private void dirTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirTextActionPerformed

    private void marcaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaTextActionPerformed

    private void bastTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bastTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bastTextActionPerformed

    private void tablaFacturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFacturasMousePressed
        //String c = (String)tablaFacturas.getValueAt(tablaFacturas.getSelectedRow(),1);
        String c = matricula(facs.get(tablaFacturas.getSelectedRow()));
        System.out.println("esa:" + matricula(facs.get(tablaFacturas.getSelectedRow())));
        System.out.println("sas:" + c);
        Coche ch;
        Cliente cl;
        if(taller.searchCoches(c).size() > 0) ch = taller.searchCoches(c).get(0);
        else ch = new Coche("-NA-","-NA-","-NA-","-NA-","-NA-","-NA-");
        if(taller.searchClientes(ch.getPropietario()).size() > 0)
        cl = taller.searchClientes(ch.getPropietario()).get(0);
        else cl = new Cliente("-NA-","-NA-","-NA-","-NA-","-NA-","-NA-","-NA-");

        marcaText.setText(ch.getMarca());
        modeloText.setText(ch.getModelo());
        kmText.setText(ch.getNumKm());
        bastText.setText(ch.getNumBast());

        nombreText.setText(cl.getNombre());
        dniText.setText(cl.getDNI());
        dirText.setText(cl.getDir());
        mailText.setText(cl.getMail());
        tlfText.setText(cl.getTlf());
        mvlText.setText(cl.getMvl());
        obsText.setText(cl.getObs());

        ArrayList<String> cochesCl = cl.getCoches();
        cochesModel.clear();
        for(int i = 0; i < cochesCl.size(); ++i){
            cochesModel.addElement(cochesCl.get(i));
        }
        cochesList.setModel(cochesModel);
    }//GEN-LAST:event_tablaFacturasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNILabel;
    private javax.swing.JToggleButton abrirFacButton;
    private javax.swing.JTextField bastText;
    private javax.swing.JButton borrarFacButton;
    private javax.swing.JList cochesList;
    private javax.swing.JLabel dirLabel;
    private javax.swing.JTextField dirText;
    private javax.swing.JTextField dniText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField kmText;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField mailText;
    private javax.swing.JTextField marcaText;
    private javax.swing.JToggleButton modClntButton;
    private javax.swing.JToggleButton modCochButton;
    private javax.swing.JToggleButton modCochtButton;
    private javax.swing.JTextField modeloText;
    private javax.swing.JLabel movilLabel;
    private javax.swing.JTextField mvlText;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreText;
    private javax.swing.JTextArea obsText;
    private javax.swing.JLabel observLabel;
    private javax.swing.JToggleButton saveClntButton;
    private javax.swing.JTable tablaFacturas;
    private javax.swing.JLabel tlfLabel;
    private javax.swing.JTextField tlfText;
    // End of variables declaration//GEN-END:variables
}
